package com.eventus.server.entity;

public enum NotificationType {
    APPROVAL_SUBMITTED,
    APPROVAL_APPROVED,
    APPROVAL_REJECTED,
    EVENT_PUBLISHED,
    EVENT_UPDATED,
    EVENT_CANCELLED,
    REGISTRATION_CONFIRMED,
    REGISTRATION_WAITLISTED,
    REGISTRATION_CANCELLED,
    WAITLIST_PROMOTED,
    ATTENDANCE_MARKED,
    WEEKLY_DIGEST
}
